# Generated by Django 4.2.1 on 2024-02-19 15:01

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='desc',
            field=tinymce.models.HTMLField(default='exit'),
            preserve_default=False,
        ),
    ]
