# Generated by Django 4.2.1 on 2024-02-19 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='desc',
        ),
    ]
