# Generated by Django 4.2.1 on 2024-02-19 18:43

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blog_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='content',
            field=models.TextField(default='exit'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='desc',
            field=tinymce.models.HTMLField(),
        ),
    ]
